name: Check Branch Name
on: push

jobs:
  branch_name:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: main
        run: | 
          echo "ref: ${{ github.ref }}"
          echo "ref_name: ${{ github.ref_name }}"
          echo "event: ${{ github.event_name }}"
          npm build
  deploy:
    needs: branch_name
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to Prod
        run: echo 'Deploying...'
